// <auto-generated />
using System;
using ApiLoja.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLoja.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230810181144_Documentos")]
    partial class Documentos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiLoja.Models.DocumentosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("DocFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ApiLoja.Models.FamiliaresModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FamiliarNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NascimentoFamiliar")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Relacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Familiares");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FotoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("ApiLoja.Models.StatusModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CIM")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Elevacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Exaltacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FoneEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FotosId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Iniciacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mae")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Naturalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pai")
                        .HasColumnType("longtext");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("longtext");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isAprendiz")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isCompanheiro")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isMestre")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("FotosId");

                    b.HasIndex("StatusId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiLoja.Models.DocumentosModels", b =>
                {
                    b.HasOne("ApiLoja.Models.UsuarioModels", null)
                        .WithMany("Documentos")
                        .HasForeignKey("UsuarioModelsId");
                });

            modelBuilder.Entity("ApiLoja.Models.FamiliaresModels", b =>
                {
                    b.HasOne("ApiLoja.Models.UsuarioModels", null)
                        .WithMany("Familiares")
                        .HasForeignKey("UsuarioModelsId");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.HasOne("ApiLoja.Models.FotosModels", "Fotos")
                        .WithMany()
                        .HasForeignKey("FotosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiLoja.Models.StatusModels", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fotos");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Familiares");
                });
#pragma warning restore 612, 618
        }
    }
}
