// <auto-generated />
using System;
using ApiLoja.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLoja.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231020140909_candidato")]
    partial class candidato
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiLoja.Models.CandidatosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AcreditaSerSupremo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Aptidoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CIM")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExpedicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSindicancia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("FamiliaConcorda")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FoneEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FotoId")
                        .HasColumnType("int");

                    b.Property<string>("Mae")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Motivos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Naturalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pai")
                        .HasColumnType("longtext");

                    b.Property<bool>("PaiMacom")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Religiao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Renda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TempoMoradia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("longtext");

                    b.Property<string>("Vicios")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("StatusId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("ApiLoja.Models.CategoriasCobrancasModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CategoriasCobrancasModels");
                });

            modelBuilder.Entity("ApiLoja.Models.CobrancasModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaCobrancaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriasCobrancasId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Pago")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriasCobrancasId");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("CobrancasModels");
                });

            modelBuilder.Entity("ApiLoja.Models.DocumentosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CandidatosModelsId")
                        .HasColumnType("int");

                    b.Property<byte[]>("DocFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GrauId")
                        .HasColumnType("int");

                    b.Property<int?>("LojaId")
                        .HasColumnType("int");

                    b.Property<int?>("LojaModelsId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatosModelsId");

                    b.HasIndex("LojaModelsId");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ApiLoja.Models.FamiliaresModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CandidatosModelsId")
                        .HasColumnType("int");

                    b.Property<string>("FamiliarNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NascimentoFamiliar")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Relacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatosModelsId");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Familiares");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosCandidatoModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FotoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FotosCandidato");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosLojasModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FotoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("LojasId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FotosLojas");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FotoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosNoticiaModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FotoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NoticiasId")
                        .HasColumnType("int");

                    b.Property<int?>("NoticiasModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoticiasModelsId");

                    b.ToTable("FotosNoticias");
                });

            modelBuilder.Entity("ApiLoja.Models.LojaModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataFundacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FotosId")
                        .HasColumnType("int");

                    b.Property<string>("Instagram")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeLoja")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroLoja")
                        .HasColumnType("int");

                    b.Property<string>("Oriente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rito")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Veneravel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FotosId");

                    b.ToTable("Lojas");
                });

            modelBuilder.Entity("ApiLoja.Models.NoticiasModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("ApiLoja.Models.StatusModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CIM")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAfiliacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Elevacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Exaltacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FoneEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FormaAfiliacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("FotoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Iniciacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LojaId")
                        .HasColumnType("int");

                    b.Property<string>("Mae")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Naturalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pai")
                        .HasColumnType("longtext");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isAprendiz")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isCandidato")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isCompanheiro")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isMestre")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("FotoId");

                    b.HasIndex("LojaId");

                    b.HasIndex("StatusId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiLoja.Models.CandidatosModels", b =>
                {
                    b.HasOne("ApiLoja.Models.FotosCandidatoModels", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId");

                    b.HasOne("ApiLoja.Models.StatusModels", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ApiLoja.Models.CobrancasModels", b =>
                {
                    b.HasOne("ApiLoja.Models.CategoriasCobrancasModels", "CategoriasCobrancas")
                        .WithMany()
                        .HasForeignKey("CategoriasCobrancasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiLoja.Models.UsuarioModels", null)
                        .WithMany("Cobrancas")
                        .HasForeignKey("UsuarioModelsId");

                    b.Navigation("CategoriasCobrancas");
                });

            modelBuilder.Entity("ApiLoja.Models.DocumentosModels", b =>
                {
                    b.HasOne("ApiLoja.Models.CandidatosModels", null)
                        .WithMany("Documentos")
                        .HasForeignKey("CandidatosModelsId");

                    b.HasOne("ApiLoja.Models.LojaModels", null)
                        .WithMany("Documentos")
                        .HasForeignKey("LojaModelsId");

                    b.HasOne("ApiLoja.Models.UsuarioModels", null)
                        .WithMany("Documentos")
                        .HasForeignKey("UsuarioModelsId");
                });

            modelBuilder.Entity("ApiLoja.Models.FamiliaresModels", b =>
                {
                    b.HasOne("ApiLoja.Models.CandidatosModels", null)
                        .WithMany("Familiares")
                        .HasForeignKey("CandidatosModelsId");

                    b.HasOne("ApiLoja.Models.UsuarioModels", null)
                        .WithMany("Familiares")
                        .HasForeignKey("UsuarioModelsId");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosNoticiaModels", b =>
                {
                    b.HasOne("ApiLoja.Models.NoticiasModels", null)
                        .WithMany("FotosNoticias")
                        .HasForeignKey("NoticiasModelsId");
                });

            modelBuilder.Entity("ApiLoja.Models.LojaModels", b =>
                {
                    b.HasOne("ApiLoja.Models.FotosLojasModels", "Fotos")
                        .WithMany()
                        .HasForeignKey("FotosId");

                    b.Navigation("Fotos");
                });

            modelBuilder.Entity("ApiLoja.Models.NoticiasModels", b =>
                {
                    b.HasOne("ApiLoja.Models.UsuarioModels", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.HasOne("ApiLoja.Models.FotosModels", "Foto")
                        .WithMany()
                        .HasForeignKey("FotoId");

                    b.HasOne("ApiLoja.Models.LojaModels", "Loja")
                        .WithMany()
                        .HasForeignKey("LojaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiLoja.Models.StatusModels", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foto");

                    b.Navigation("Loja");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ApiLoja.Models.CandidatosModels", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Familiares");
                });

            modelBuilder.Entity("ApiLoja.Models.LojaModels", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("ApiLoja.Models.NoticiasModels", b =>
                {
                    b.Navigation("FotosNoticias");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.Navigation("Cobrancas");

                    b.Navigation("Documentos");

                    b.Navigation("Familiares");
                });
#pragma warning restore 612, 618
        }
    }
}
