// <auto-generated />
using System;
using ApiLoja.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiLoja.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260717195701_AddComunicados")]
    partial class AddComunicados
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiLoja.Models.CandidatosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AcreditaSerSupremo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Aptidoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExpedicao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataSindicancia")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("FamiliaConcorda")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FoneEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Mae")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Motivos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Naturalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pai")
                        .HasColumnType("longtext");

                    b.Property<bool>("PaiMacom")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuemIndica")
                        .HasColumnType("int");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Religiao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Renda")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TempoMoradia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("longtext");

                    b.Property<string>("Vicios")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Candidatos");
                });

            modelBuilder.Entity("ApiLoja.Models.CargosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cargos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Venerável Mestre"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Tesoureiro"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Secretário"
                        });
                });

            modelBuilder.Entity("ApiLoja.Models.CategoriaFinanceiroModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CategoriasFinanceiro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Mensalidade",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Mútua",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Joia",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Medalha",
                            Tipo = "Entrada"
                        },
                        new
                        {
                            Id = 5,
                            Nome = "Aluguel",
                            Tipo = "Saida"
                        },
                        new
                        {
                            Id = 6,
                            Nome = "Capitação GOSP",
                            Tipo = "Saida"
                        },
                        new
                        {
                            Id = 7,
                            Nome = "Mútua",
                            Tipo = "Saida"
                        },
                        new
                        {
                            Id = 8,
                            Nome = "Insumos",
                            Tipo = "Saida"
                        },
                        new
                        {
                            Id = 9,
                            Nome = "Ágape",
                            Tipo = "Saida"
                        },
                        new
                        {
                            Id = 10,
                            Nome = "Medalha",
                            Tipo = "Saida"
                        },
                        new
                        {
                            Id = 11,
                            Nome = "Placets",
                            Tipo = "Saida"
                        });
                });

            modelBuilder.Entity("ApiLoja.Models.CategoriasCobrancasModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoriaNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CategoriasCobrancas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaNome = "Mensalidade"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaNome = "Mútua"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaNome = "Joia"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaNome = "Medalha"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaNome = "Placets"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaNome = "Outros"
                        });
                });

            modelBuilder.Entity("ApiLoja.Models.CobrancasModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaCobrancaId")
                        .HasColumnType("int");

                    b.Property<int>("CategoriasCobrancasId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Pago")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.Property<DateTime>("Vencimento")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriasCobrancasId");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Cobrancas");
                });

            modelBuilder.Entity("ApiLoja.Models.ComunicadosFotoModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ComunicadoId")
                        .HasColumnType("int");

                    b.Property<string>("FotoFile")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FotoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ComunicadoId");

                    b.ToTable("ComunicadosFotos");
                });

            modelBuilder.Entity("ApiLoja.Models.ComunicadosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Graus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Comunicados");
                });

            modelBuilder.Entity("ApiLoja.Models.DocumentosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<int?>("CandidatosModelsId")
                        .HasColumnType("int");

                    b.Property<byte[]>("DocFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("DocName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("GrauId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatosModelsId");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("ApiLoja.Models.FamiliaresModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CandidatosModelsId")
                        .HasColumnType("int");

                    b.Property<string>("FamiliarNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("NascimentoFamiliar")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Relacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CandidatosModelsId");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Familiares");
                });

            modelBuilder.Entity("ApiLoja.Models.FinanceiroModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaFinanceiroId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaFinanceiroId");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Financeiro");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosCandidatoModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CandidatoId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FotoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FotosCandidato");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosNoticiaModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<byte[]>("FotoFile")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<string>("FotoName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NoticiasId")
                        .HasColumnType("int");

                    b.Property<int?>("NoticiasModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NoticiasModelsId");

                    b.ToTable("FotosNoticias");
                });

            modelBuilder.Entity("ApiLoja.Models.FrequenciaModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataReuniao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Presente")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("UsuarioModelsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioModelsId");

                    b.ToTable("Frequencia");
                });

            modelBuilder.Entity("ApiLoja.Models.LivrosModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isAprendiz")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isCompanheiro")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isMestre")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Livros");
                });

            modelBuilder.Entity("ApiLoja.Models.NoticiasModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AutorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AutorId");

                    b.ToTable("Noticias");
                });

            modelBuilder.Entity("ApiLoja.Models.StatusModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("ApiLoja.Models.TokenModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuemIndica")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Token");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CIM")
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("CargoId")
                        .HasColumnType("int");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContatoEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAfiliacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInstalacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("Elevacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Exaltacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Fone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FoneEmergencia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FormaAfiliacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Iniciacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mae")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Naturalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Pai")
                        .HasColumnType("longtext");

                    b.Property<string>("Pass")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Profissao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RG")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<string>("TipoSanguineo")
                        .HasColumnType("longtext");

                    b.Property<bool>("isAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isAprendiz")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isCandidato")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isCompanheiro")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isMestre")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isMestreInstalado")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("StatusId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ApiLoja.Models.CandidatosModels", b =>
                {
                    b.HasOne("ApiLoja.Models.StatusModels", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ApiLoja.Models.CobrancasModels", b =>
                {
                    b.HasOne("ApiLoja.Models.CategoriasCobrancasModels", "CategoriasCobrancas")
                        .WithMany()
                        .HasForeignKey("CategoriasCobrancasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiLoja.Models.UsuarioModels", "Usuario")
                        .WithMany("Cobrancas")
                        .HasForeignKey("UsuarioModelsId");

                    b.Navigation("CategoriasCobrancas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiLoja.Models.ComunicadosFotoModels", b =>
                {
                    b.HasOne("ApiLoja.Models.ComunicadosModels", "Comunicado")
                        .WithMany("FotosComunicados")
                        .HasForeignKey("ComunicadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comunicado");
                });

            modelBuilder.Entity("ApiLoja.Models.ComunicadosModels", b =>
                {
                    b.HasOne("ApiLoja.Models.UsuarioModels", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("ApiLoja.Models.DocumentosModels", b =>
                {
                    b.HasOne("ApiLoja.Models.CandidatosModels", null)
                        .WithMany("Documentos")
                        .HasForeignKey("CandidatosModelsId");

                    b.HasOne("ApiLoja.Models.UsuarioModels", null)
                        .WithMany("Documentos")
                        .HasForeignKey("UsuarioModelsId");
                });

            modelBuilder.Entity("ApiLoja.Models.FamiliaresModels", b =>
                {
                    b.HasOne("ApiLoja.Models.CandidatosModels", null)
                        .WithMany("Familiares")
                        .HasForeignKey("CandidatosModelsId");

                    b.HasOne("ApiLoja.Models.UsuarioModels", null)
                        .WithMany("Familiares")
                        .HasForeignKey("UsuarioModelsId");
                });

            modelBuilder.Entity("ApiLoja.Models.FinanceiroModels", b =>
                {
                    b.HasOne("ApiLoja.Models.CategoriaFinanceiroModels", "CategoriaFinanceiro")
                        .WithMany()
                        .HasForeignKey("CategoriaFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiLoja.Models.UsuarioModels", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioModelsId");

                    b.Navigation("CategoriaFinanceiro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiLoja.Models.FotosNoticiaModels", b =>
                {
                    b.HasOne("ApiLoja.Models.NoticiasModels", null)
                        .WithMany("FotosNoticias")
                        .HasForeignKey("NoticiasModelsId");
                });

            modelBuilder.Entity("ApiLoja.Models.FrequenciaModels", b =>
                {
                    b.HasOne("ApiLoja.Models.UsuarioModels", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioModelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ApiLoja.Models.NoticiasModels", b =>
                {
                    b.HasOne("ApiLoja.Models.UsuarioModels", "Autor")
                        .WithMany()
                        .HasForeignKey("AutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.HasOne("ApiLoja.Models.CargosModels", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId");

                    b.HasOne("ApiLoja.Models.StatusModels", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("ApiLoja.Models.CandidatosModels", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Familiares");
                });

            modelBuilder.Entity("ApiLoja.Models.ComunicadosModels", b =>
                {
                    b.Navigation("FotosComunicados");
                });

            modelBuilder.Entity("ApiLoja.Models.NoticiasModels", b =>
                {
                    b.Navigation("FotosNoticias");
                });

            modelBuilder.Entity("ApiLoja.Models.UsuarioModels", b =>
                {
                    b.Navigation("Cobrancas");

                    b.Navigation("Documentos");

                    b.Navigation("Familiares");
                });
#pragma warning restore 612, 618
        }
    }
}
